[package]
name = "rust_proj"
version = "0.1.0"
authors = ["Jeremy Linton <lintonrjeremy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"

[[bin]]
name = "rust_proj"
path = "main.rs"
